baseURL = "http://localhost:1313"
title = "Roo Recipes"

theme = "puppet"

copyright = ""
paginate = 5
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50

[params]
author = "Chef Roo"
description = ""
keywords = "blog,developer,personal"
img_home = ""
img_404 = "img/404-bg2.jpg"
logo_img = "img/Logo.svg"
cheff_roo = "img/chefroo.png"
wave = "img/wave.svg"

useFaviconGenerator = true

custom_js = []
custom_css = ["sass/custom.scss"] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/about-me.jpg"
bio = "Part-time artists who likes to cook as a hobby. This is my personal recipe book"

[params.social]
twitter = "johndoe"
rss = false
[params.social.mastodon]
weight = 56
icon = "fab fa-mastodon"
format = "https://mastodon.social/%v"
id = "johndoe"
url = ""



# See https://giscus.app/
[params.giscus]
enable = true
repo = "roninro/hugo-theme-puppet"
repo_id = "R_kgDOHuvyhw"
category = "General"
category_id = "DIC_kwDOHuvyh84CQjDo"
input_position = "top"
theme = "light_tritanopia"
lang = "en"
